# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: HammondDesign
email: jbhammon@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  Hi! I'm Jackson Hammond, Healthcare IT Professional with a passion for
  excellent design. Here is where I'll be posting updates about creative projects
  I'm spending my spare time on. I hope you enjoy!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: None!
github_username:  jbhammon

# Build settings
markdown: kramdown
